### ISSUE TITLE
Txn.findCurrent finds discarded transactions?

### ISSUE THREAD

**Issue by Sciss** [scala-stm/scala-stm#14]
I'm seeing something like this:
```scala
java.lang.IllegalStateException: no active transaction
	at scala.concurrent.stm.ccstm.InTxnImpl.requireActive(InTxnImpl.scala:889)
	at scala.concurrent.stm.ccstm.InTxnRefOps.swap(InTxnRefOps.scala:278)
	at scala.concurrent.stm.ccstm.ViewOps.swap(ViewOps.scala:43)
	at scala.concurrent.stm.ccstm.ViewOps.swap$(ViewOps.scala:41)
	at scala.concurrent.stm.ccstm.CCSTMRefs$BaseRef.swap(CCSTMRefs.scala:46)
	at de.sciss.proc.impl.FScapeRunnerImpl$Impl$progress$.push(FScapeRunnerImpl.scala:80)
```
where the last line is
```scala
timerRef.single.swap(None).foreach(_.cancel())
```
and `timerRef` is a `Ref`.

In another place I'm likewise sometimes finding a transaction through `Txn.findCurrent` that was "left behind" by this `.single` operation (which sometimes succeeds). When printed its `toString` says `Detached`.

I see this check
```scala
private def active(txn: InTxnImpl): InTxnImpl = if (txn.internalCurrentLevel != null) txn else null
```
but I can't say why it would detect non-null and thus an active transaction?

@nbronson any idea what might be going on?

**Comment by Sciss** [comment]
perhaps it's worth saying this is from some Akka execution context:
```
[ERROR] [11/26/2020 17:23:55.338] [fscape-akka.actor.internal-dispatcher-3] [akka://fscape/user/$m] no active transaction
```
